accessing
dicoCouleur
	^ {(1
		->
			(Color r: 0.712 g: 0.736 b: 0.736 alpha: 1.0)).
	(2
		->
			(Color
				r: 0.438
				g: 0.979
				b: 0.9570000000000001
				alpha: 1.0)).
	(3
		->
			(Color
				r: 0.089
				g: 0.079
				b: 0.851
				alpha: 1.0)).
	(4
		->
			(Color
				r: 0.986
				g: 0.401
				b: 0.759
				alpha: 1.0)).
	(5
		->
			(Color
				r: 0.891
				g: 0.035
				b: 0.035
				alpha: 1.0))} asDictionary